SCR_LoadingScreenHints {
 m_aHints {
  "Make sure to thank the pilot when you exit the dropship."
  "hey you! remember to google \"people who did nothing wrong\". Thanks."
  "¯\_(ツ)_/¯"
  "Tip: Backblasting your teammates is fucking hilarious. It's also against the rules."
  "Reminder: praying to any kind of religous figure is illegal and punishible by recloning. Thanks :)"
  "Between you and me that thing that killed your previous clone is a total dick. Please disregard this message if you committed suicide."
  "didievertellyouaboutthisonetimewhenibuildtheentireoperationmapandthenitstoppedworkinganditdidntworkforlike10versionsitwasGREAT"
  "\"idk who this guy is but he's a right prick.\" - Unknown"
  "Fun Fact: You will answer for your crimes."
  "Did you know that your mother."
  "\"My firsts words were I am having sex with your mother.\""
  "Why do I taste penneys"
  "I dont love you."
  "1MB Company Meeting - spoons in saaaaaaf landann"
  "<insert loading screen here>"
  "Nyk will cum cum"
  "\"I dont have testicles\" - Tsc. SK"
  "the USC has determined your injury is not service related"
  "Holy shit"
  "HOLY SHIT"
  "\"Your clones may have extra appendages such as arms legs and genitals\" - Pfc. Knockoffjedi"
  "(edited)"
  "Hello there. I am phoning you today about your childs extended warrenty. Unfortunately your child has expired. Please buy a new one and try again."
  "Don't try to remember how your previous clone died. Your head may explode."
  "Good news: You died :)"
  "Not so fun fact: Geek is the only pilot who can land every aircraft"
  "Qwazer 0 - Ground 115"
  "I love watching qwazer perform manouver kills on himself"
  "\"I swear to God I will fist you\" - Pfc. Knockoffjedi"
  "\"GET OUT\" - IAO. Geek-x"
  "\"Madri is shit\" - Tsc. SK"
  "\"Fuck you.\" - Unknown."
  "\"just rawdog it\" - ECO-T. Særgo"
  "\"i like hard men\" - Lt. Croc"
  "\"don't quote me\" - Lcpl. Arrow"
  "Infinite Monkey Theorem - The infinite monkey theorem states that a monkey hitting keys independently and at random on a typewriter keyboard for an infinite amount of time will almost surely type any given text - including the complete works of William Shakespeare."
  "Sinker 0 - Balcony 1"
  "ALL MY APES! GONE!!"
  "He gave me the 2 dollar bill that was enough for me"
  "SAAAAAAF LANDAAAANNNNN"
  "You. Yes you. I'm talking to you. Keep yourself safe tonight."
  "They're in your walls."
  "CRG has no negative side-effects to your health! (study paid for by GALACTICURE 'GALACTICURE: put your health in our hands')."
  "WHO ATE THE ARSENAL BOX??!"
  "Big brother is always watching"
  "Steadfast doesn't know the lyrics to Grace Kelly"
  "Remember to tune your handhelds to 104.5 and listen to United Solar Radio today!"
  "Kill Clankers. Behead Wirebacks. Roundhouse kick copper munchers into the concrete. Slam dunk an oil-drinker baby into the trashcan."
  "Fun bug fact: I'm watching you"
  "I'm shivering my timbers right now"
  "My timbers are thoroughly shivered"
  "Galactic Forces Mod out now!"
  "Nice argument... however - your mother."
  "STEADFAST IS FUCKIN'"
  "Wordle is a fucking scam."
  "I'm gonna rub ur belly"
  "Tip: why did he leave"
  "Please refrain from flirting with your datapad"
  "nee naw nee naw"
  "Go go gadget reduce fps"
  "I was a loading screen tip once..."
  "Fun Bug Fact! He draws near. Your end approaches."
  "psst! hes behind you"
  "OH SHIT ITS SINKER"
  "Do I get travel miles? No FUCK OFF"
  "Everyone is entitled to a fair trial. (totally)"
  "Knockoffjedi likes older women"
  "Hello I am under the water please help me"
  "Tip..."
  "https://www.twitch.tv/directorsinker"
  "https://www.twitch.tv/geek_x104"
  "https://sites.google.com/view/unitedsolarcommand/home"
  "https://x.com/104thMilsim"
  "https://www.youtube.com/@UnitedSolarCommand"
  "https://www.instagram.com/104th_battalion_milsim/"
 }
}