SCR_LoadingScreenHints {
 m_aHints {
  "Make sure to thank the pilot when you exit the dropship."
  "¯\_(ツ)_/¯"
  "Tip: Backblasting your teammates is fucking hilarious. It's also against the rules."
  "Reminder: praying to any kind of religous figure is illegal and punishible by recloning. Thanks :)"
  "Between you and me that thing that killed your previous clone is a total dick. Please disregard this message if you committed suicide."
  "didievertellyouaboutthisonetimewhenibuildtheentireoperationmapandthenitstoppedworkinganditdidntworkforlike10versionsitwasGREAT"
  "\"idk who this guy is but he's a right prick.\" - Unknown"
  "Fun Fact: You will answer for your crimes."
  "\"My firsts words were I am having sex with your mother.\""
  "I dont love you."
  "Holy shit"
  "HOLY SHIT"
  "(edited)"
  "Hello there. I am phoning you today about your childs extended warrenty. Unfortunately your child has expired. Please buy a new one and try again."
  "Don't try to remember how your previous clone died. Your head may explode."
  "Good news: You died :)"
  "Not so fun fact: Geek is the only pilot who can land every aircraft"
  "Qwazer 0 - Ground 115"
  "I love watching qwazer perform manouver kills on himself"
  "\"I swear to God I will fist you\" - Pfc. Knockoffjedi"
  "\"GET OUT\" - IAO. Geek-x"
  "\"Madri is shit\" - Tsc. SK"
  "\"Fuck you.\" - Unknown."
  "\"just rawdog it\" - ECO-T. Særgo"
  "\"i like hard men\" - Lt. Croc"
  "\"don't quote me\" - Lcpl. Arrow"
  "Infinite Monkey Theorem - The infinite monkey theorem states that a monkey hitting keys independently and at random on a typewriter keyboard for an infinite amount of time will almost surely type any given text - including the complete works of William Shakespeare."
  "Sinker 0 - Balcony 1"
  "ALL MY APES! GONE!!"
  "He gave me the 2 dollar bill that was enough for me"
  "SAAAAAAF LANDAAAANNNNN"
  "You. Yes you. I'm talking to you. Keep yourself safe tonight."
  "They're in your walls."
  "WHO ATE THE ARSENAL BOX??!"
  "Big brother is always watching"
  "Steadfast doesn't know the lyrics to Grace Kelly"
  "Remember to tune your handhelds to 104.5 and listen to United Solar Radio today!"
  "Fun bug fact: I'm watching you"
  "I'm shivering my timbers right now"
  "My timbers are thoroughly shivered"
  "Galactic Forces Mod out now!"
  "Nice argument... however - your mother."
  "STEADFAST IS FUCKIN'"
  "I'm gonna rub ur belly"
  "nee naw nee naw"
  "Go go gadget reduce fps"
  "I was a loading screen tip once..."
  "psst! hes behind you"
  "OH SHIT ITS SINKER"
  "Do I get travel miles? No FUCK OFF"
  "Everyone is entitled to a fair trial. (totally)"
  "Hello I am under the water please help me"
  "Tip..."
  "https://www.twitch.tv/directorsinker"
  "https://www.twitch.tv/geek_x104"
  "https://x.com/104thMilsim"
  "https://www.youtube.com/@UnitedSolarCommand"
  "https://www.instagram.com/104th_battalion_milsim/"
  "hi im joe bidens husband"
  "\"I have 2 younger brothers im the oldest of 3 and ive got a sister whos the love of my life\""
 }
}